image: fedora:latest

before_script:
  - dnf update -y
  - dnf install -y gcc automake libtool make pkgconfig autoconf-archive nss-devel glib2-devel opensc gnutls-utils nss-tools openssl softhsm lcov valgrind libasan clang csbuild which

Build:
  stage: build
  script:
    - ./autogen.sh
    - make

Check:
  stage: test
  script:
    - ./autogen.sh --enable-code-coverage
    - make check
    - make code-coverage-capture
    - lcov --summary libcacard-*-coverage.info
  artifacts:
    expire_in: '1 week'
    paths:
      - test-suite.log
      - libcacard-*-coverage

Memcheck:
  stage: test
  script:
    - ./autogen.sh
    - make memcheck-local
  allow_failure: true

asan:
  stage: test
  variables:
    ASAN_OPTIONS: fast_unwind_on_malloc=false
  script:
    - ./autogen.sh
    - make CFLAGS="-fsanitize=address" check || (cat test-suite.log && exit 1)
  artifacts:
    expire_in: '1 week'
    paths:
      - test-suite.log
  allow_failure: true

clang:
  stage: build
  variables:
    CC: clang
  script:
    - ./autogen.sh
    - make
  artifacts:
    expire_in: '1 week'
    paths:
      - test-suite.log
  allow_failure: true

csbuild:
  stage: test
  script:
    - csbuild
      --prep-cmd="./autogen.sh"
      --build-cmd "make clean && make"
      --color
      --print-current

pages:
  stage: deploy
  dependencies:
    - Check
  script:
    - mv *-coverage/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master
